### ISSUE TITLE
Error while Getting Token

### ISSUE THREAD

**Issue by fynnsh** [bilbo-b/niu-api.py#3]
Is there a new API? Or are you Still using this Script?

Traceback (most recent call last):
  File "niu.py", line 96, in <module>
    token = get_token()
  File "niu.py", line 27, in get_token
    return data['data']['token']
KeyError: 'token'

**Comment by binderth** [comment]
once in a while you have to manually delete the downloaded token (_saved_token.txt_). the script will then automatically generate a new one.
at least that's what I have to do after a few months.
